main/init.f90

zvar was indexed in the wrong dimension when averageing between layers for geopotential height

fixed bug in init z variable

---

io/lt_lut_io.f90
main/data_structures.f90
main/init_options.f90
main/time_step.f90
physics/linear_winds.f90
physics/mp_driver.f90
physics/mp_thompson.f90

- namelist mp_parameters now support option update_interval and this code works
- microphysics will only be updated as close to a maximum time interval (update_interval) as possible
- Changed lt_lut_io to create 64-bit offset files so it can write variables greater than 2GB in size. 
- Added check for z_is_geopotential=False and zvar="PH" (will print warning)
- fixed gfortran bug (can't use == to compare logicals)
- will now write the lt_lut if write=true and read=true when there is an error reading. 
- added more doxygen headers, added a better check for qv<0 in mp_thompson

bug fixes + mp update_interval works

---

io/lt_lut_io.f90

Previous change to 64-bit offset files only supported >2GB variables, but LUTs can be larger still! 
Now requiring LUTs to be NetCDF4 files (requires HDF5 support) at some point I probably need to add a line that tests for HDF5 support and simply doesn't read (or write) LUTs if it is not available.

made lt_lut files NF90_NETCDF4 to support >4GB variable

---

helpers/setup_next_run.py
io/output.f90
main/boundary.f90
main/data_structures.f90
main/init.f90
main/init_options.f90
main/time_step.f90
physics/linear_winds.f90
physics/mp_driver.f90
physics/ra_simple.f90
run/complete_icar_options.nml
utilities/debug_utils.f90
utilities/time.f90

Adds capability to bias correct (microphysics only) precipitation at runtime ("online").  
Adds ability to turn % completed printing on / off with interactive = true/false in the parameters namelist
Adds surface pressure and ~hourly snowfall amounts to output files
Permits negative values to be specified for top_mp_level in which case top_mp_level will be specified as nz + top_mp_level
Various bug fixes

online biascorrection

---

mkdocs.yml

This should be it.  Once you merge it, I'll test it...

adding analytics to ICAR's readthedocs page

---

run/complete_icar_options.nml
src/main/boundary.f90
src/main/data_structures.f90
src/main/init_options.f90
src/makefile
src/physics/ra_simple.f90
src/utilities/atm_utilities.f90
src/utilities/geo_reader.f90

Now permits input humidity to be relative, specific, or mixing ratio. 
Also permits input temperature to be real instead of potential. 
Fixes possible bug in georeader if a point was too close to a line (precision issues), may need to think about this more generally still. 
Finally checks to see that dz levels were read in correctly from the namelist (e.g. there are no negative dz values specified).  Before a namelist that worked with ifort would cause random seeming errors with gfortran because of how the two compilers treat reading in arrays from namelists.

Merge various bug fixes and updates, adds humidity and temperature options

---

helpers/wrf2icar.sh
src/tests/test_point_in_on.f90
src/utilities/geo_reader.f90

Relaxes precision on geo_reader's point in poly test so a point only has to fall within one meter of a polygon to count as being "in" the polygon.  This was causing problems with an edge case in which the point fell on a line, but due to numerical precision issues (order of operations dependent) it didn't appear to be in the polygons on either side of the line.  
Also adds a wrf2icar script that can be used to convert WRF output (or metgrid output) files into icar input files.  Note this script depends on NCO, has hardcoded variable names (WRF's current standard names).  This could be cleaned up, but it meant to provide a starting point for any other interested parties.

Minor update to geo_reader and adds a wrf2icar helper script

---

src/io/output.f90

The stored value is actually the natural logarithm of the squared quantity. Updated the corresponding field attributes that are written to the output files to correctly reflect that.
all now indicate that the stored value is the natural logarithm of the squared Brunt Vaisala frequency.

updated standard_name, long_name and unit of nsq field in output

---

src/main/boundary.f90
src/main/data_structures.f90
src/main/init_options.f90

This update adds the capability to specify additional microphysics fields that should be imported from the forcing dataset. Their behaviour is the same as for the already pre-existing optional fields such as cloud ice mixing ratio and cloud water mixing ratio. If specified these fields are also applied at the domain boundaries during the simulation. The new optional fields are:
- qrvar ... rain mixing ratio [kg/kg]
- qsvar ... snow mixing ratio [kg/kg]
- qgvar ... graupel mixing ratio [kg/kg]
- qnivar ... ice number density [1/kg]
- qnrvar ... rain number density [1/kg]
and must be specified in the var_list section of the icar options file.
**Example**
if a WRF simulation is used as forcing dataset and the additional microphysics fields should be used:
qrvar = "QRAIN", ! rain mixing ratio …

Additional microphysics fields for initialisation and domain boundaries

---

src/main/boundary.f90
src/main/data_structures.f90
src/main/init.f90
src/main/init_options.f90
src/main/time_step.f90

If set to true ICAR calculates the atmospheric stability within the ICAR domain from the current state of the forcing data set instead of the ICAR domain. This is in agreement with the theoretical basis of ICAR,  linear mountain-wave theory, where atmospheric stability is considered a property of the atmospheric background state and not of the perturbed atmosphere. In case of ICAR, the background state is given by the forcing.
The standard behaviour of ICAR is preserved, to activate this behaviour set `N_from_forcing = .True.` in the `lt_parameters` namelist in the options file of ICAR.

Added the option N_from_forcing to the linear theory namelist.

---

src/physics/linear_winds.f90

As described in the description there was a bug that led to N varying even though a fixed value of N was prescribed in the ICAR options and variable_N was set to false. A workaround was to set spatial_variable_fields to False as well. This is now fixed, it now works as intended.
Additionally all N calculations were moved into an if-clause that is only triggered if variable_N=True.

fixed a bug that cause N to vary even though variable_N=False

---

src/main/boundary.f90
src/main/data_structures.f90
src/main/init_options.f90
src/physics/linear_winds.f90

The Brunt-Vaisala frequency N can now be read from a field in theforcing dataset. To do so N_from_forcing in the linear theory options must be set to true and the name of the field that contains the squared Brunt Vaisala frequency must be set in the ICAR options with the option nvar.
**Note:** the field in the forcing dataset must store N^2.
The following plot show the resulting difference in the Brunt-Väisälä frequency field due to different calculation methods:
- The uppermost panel plots log(N^2) used by ICAR for the case where ICAR calculates it from the state of the atmosphere in the ICAR domain - this is the default behavior so far.
- The middle panel plots log(N^2) used by ICAR for the case where it is read from a field in the forcing dataset. This is the result if the options …

 N can now be read in from a field in the forcing data

---

src/utilities/geo_reader.f90

Increased the maximum acceptable error in triangulation weights to 0.01.  This is particularly useful for very high resolution grids (<<1km) because that pushes what a float can reliably reproduce when a lat lon values may be O(100).  As a result, the method that finds the bounding points and the method that computes the weights end up with very slightly different values (because they are doing different things), and one of the weights can be <-1e-3 (the previous criteria).  It now accepts such negative weights, sets them to 0, and renormalizes the remaining weights.

tweaked interpolation error testing for float precision

---

src/makefile

This PR contains two small modifications.
*) The documentation in the Makefile suggests setting the environmental variables LIBFFT and INCFFT. These variables are created further on in the Makefile using the variable FFTW. If FFTW is not set, then FFTW_PATH defaults to /usr/local/.
*) Change mpi fortran compiler from mpif90 to mpiifort. mpif90 is a compiler wrapper to mpiifort on Cheyenne, but this is a special case. This is confusing as mpif90 is the default name for the gfortran mpi compiler. Change to mpiifort, which still works on Cheynne and is portable.

Small changes to Makefile for portability.

---

src/main/driver.f90
src/main/init.f90

Moves the physics driver initialization out of init_model into the main driver so that it can be called after restart data are read in.

Fix for restart initialization problem

---

helpers/wrf2icar.sh

TYPE: bug fix
KEYWORDS: bug fix, helper code
DESCRIPTION OF CHANGES: Updated wrf2icar.sh file.  There was a problem with flags used in an nco operator (when removing the time dimension from XLAT and XLONG).  The -C flag was added to avoid errors.

added -C flag for xlat/xlong in wrf2icar.sh

---

helpers/erai/convert.py
helpers/erai/io_routines.py
helpers/erai/output.py
src/io/output_h.f90
src/io/output_obj.f90

Update the output_obj.f90 object to write a "calendar" attribute to the netcdf time variable to store the calendar being used. 
TYPE: 
bugfix
KEYWORDS: 
time, climate model, calendar
SOURCE: 
Ethan Gutmann, NCAR
Modified time objects setup_time_variable routine to test for the value of the time objects calendar attribute.  Use that attribute to set a calendar attribute in the resulting netcdf time variable. 
ISSUE: 
Previously calendar would not be specified, when using GCMs with a noleap or 360-day calendar, this would result in incorrect date stamps (as they would by default be interpreted in a gregorian calendar).

added calendar attribute to output files

---

src/objects/opt_types.f90
src/objects/options_h.f90
src/objects/options_obj.f90
src/physics/ra_driver.f90
src/physics/ra_rrtmg_lw.f90
src/physics/ra_rrtmg_sw.f90
src/utilities/atm_utilities.f90

TYPE: enhancement
KEYWORDS: cloud interaction with radiation, added namelist options, added calculation of 3d cloud fraction 
SOURCE: Trude Eidhammer
DESCRIPTION OF CHANGES: 1) Fixed a bug which caused RRTMG short wave code to not interact with clouds. 
2) User can now chose the iCloud option to use and the time step between RRTMG update in the namelist. 
3) Added the Thompson routine of calculating 3D cloud fraction from WRF
TESTS CONDUCTED: 
Compared the updates with the simple radiation scheme, and with icloud = 0 (icloud=0 means no cloud impact on radiation) 
Figure shows 2m average daily temperature difference (in Kelvin). Left plot is the difference between RRTMG icloud =3 and the simple radiation scheme. Right plot is the difference between RRTMG icloud=3 and RRTMG icloud=0 …

Updates to RRTMG code to improve/implement cloud feedbacks

---

src/objects/opt_types.f90
src/objects/options_obj.f90
src/physics/ra_driver.f90
src/physics/ra_rrtmg_lw.f90

TYPE: enhancement
KEYWORDS: Greenhouse Gas, CMIPs 
SOURCE: Trude Eidhammer, NCAR
DESCRIPTION OF CHANGES: There is now a namelist option for RRTMG where the user can choose to read in projected greenhouse gas mixing ratio for several different CMIP scenarios. The files are located in icar_supporting_files/rrtmg_support and labeled as CAMtr_volume_mixing_ratio.xxx
In the run directory, the user should create a link CAMtr_volume_mixing_ratio that links to the desired CAMtr_volume_mixing_ratio.xxx file. 
To run this new capability, the user need to set the namelist parameter 
run_ghg = .true.
TESTS CONDUCTED: Compiled and run
Merging the PR depends on following checklist being completed. Add `X` between
each of the square brackets if they are completed in the PR itself. If a
bullet is not …

Added the posibility to read in greenhouse gas files when using RRTMG

---

src/physics/adv_mpdata.f90
src/physics/adv_mpdata_FCT_core.f90
src/physics/advect.f90
src/physics/wind.f90

TYPE: No impact (refactoring)
KEYWORDS: Advection, coordinate-transform, refactoring
SOURCE: Dylan Reynolds, SLF
DESCRIPTION OF CHANGES: As requested by Ethan, ensured that references to jacobian of coordinate transform are minimized throughout the code, and that the check in advection of winds is guaranteed the same as what is used in the actual advection. The indexing of arrays in the advection code has also been changed to image-scope indexing (ims:ime, etc) to be consistent with rest of v2 code.

Changed advect.f90 winds check, cleaned up wind.f90 smooth_height references

---

src/makefile

TYPE: bugfix
KEYWORDS: NetCDF, makefile, library paths
DESCRIPTION OF CHANGES: Some installations of NetCDF has different locations for the C library and the Fortran library. If the environmental variable NETCDFF is defined, that path will also be searched when building.
TESTS CONDUCTED: Built and ran full test domain on NERSC's Cori in parallel.

bugfix: adding NETCDFF variable in makefile

---

src/objects/domain_obj.f90

flat model height <0 is now possible with SLEVE again (this was accidentally turned off in commit  d5a70131d374932b555a7e44f0785e4a06af5f4e )
TYPE: bug fix
bug fix of earlier 'error' in pr 108, where setting flat dz != 0 was overwritten to flat_dz_height=0 (with output warnings)
SOURCE: Bert Kruyt, NCAR
See lines 942-950 in domain_obj, commented out lines that forced max_level to be equal to nz.

 flat model height <0 is now possible with SLEVE

---

src/objects/boundary_obj.f90

TYPE: bug fix
KEYWORDS: forcing, computed variables, relative humidity
SOURCE: Ethan Gutmann, NCAR
Fix a problem that occurs if forcing data are provided with relative humidity and potential temperature.  Previously ICAR would not convert potential temperature to real temperature before computing water vapor mixing ratio from relative humidity.  This lead to some crazy results, not it checks what the form of temperature is before calculating humidity. 
ISSUE: none
TESTS CONDUCTED: 
Ideal test case was run before and after change and output mixing ratios make sense now.

Fix for potential temperature & relative humidity forcing combination

---

src/constants/icar_constants.f90
src/objects/domain_obj.f90
src/physics/wind.f90
src/utilities/array_utilities.f90

TYPE: bug fix & enhancement
KEYWORDS: iterative winds, flat_z_height, wind
SOURCE: Ethan Gutmann, NCAR
Primarily, this is a fix for issue #129 . This issue noted that upper level winds in icar could contain anomalous vertical motion when the flat Z height was set somewhere below the model top and the iterative wind solver was used (wind=3). Here we have modified the domain object so that the max level is set to the top of the model, and in the iterative wind solver we have modified wind_K to always defaults to the top of the model. Because there is some potentially valuable behavior in the old configuration, most of that code was left in but commented out.
In addition, this pull request has cleaned up some of the array 2-D/3-D calls to the array utilities, and …

Fix upper wind anomaly with iterative winds and lower flat z height

---

run/complete_icar_options.nml
src/constants/icar_constants.f90
src/constants/wrf_constants.f90
src/makefile
src/physics/cu_bmj.f90
src/physics/cu_driver.f90
src/physics/cu_nsas.f90
src/utilities/debug_utils.f90

TYPE:  enhancement, new feature
KEYWORDS: convection, NSAS, BMJ
SOURCE: Bert Kruyt, NCAR RAL
DESCRIPTION OF CHANGES: this PR includes the addition of the NSAS as BMJ convection schemes. Both schemes were copied from the WRF 4.4 code base, and modified to prevent out of bound errors in the case of low model tops.
TESTS CONDUCTED: Runs as before. BMJ significantly increases convective precipitation compared to Tiedtke.
NOTES: both NSAS and BMJ require PBL height (absolute or in the form of a z-level index (in the case of BMJ) ) as an input. Currently , the PBL scheme in ICAR does not compute a PBL height. Therefore, the PBL height is hardcoded as a arbitrary, uniform, fixed value above the ground in cu_driver.f90. Sensitivity tests will be conducted to see how sensitive the schemes are to …

BMJ and NSAS convection

---

src/physics/cu_bmj.f90

TYPE: bug fix
KEYWORDS: BMJ, warning, logfile
SOURCE: Bert Kruyt, NCAR
DESCRIPTION OF CHANGES: BMJ convection scheme was modified to prevent crash with a low modeltop. This outputted a warning for each time this condition was met, leading to many, many warnings in the model output or logfile, even potentially crashing it on long runs. This warning is now commented out so the model output is clean. 
TESTS CONDUCTED: None. just a write(*,*) statement removed.
Merging the PR depends on following checklist being completed. Add `X` between
each of the square brackets if they are completed in the PR itself. If a
bullet is not relevant to you, please comment on why below the bullet.
describes the technical details of the …

removal of  BMJ 'low modeltop' warning

---

run/complete_icar_options.nml
src/constants/icar_constants.f90
src/io/default_output_metadata.f90
src/io/output_obj.f90
src/io/restart.f90
src/makefile
src/objects/domain_h.f90
src/objects/domain_obj.f90
src/objects/opt_types.f90
src/objects/options_obj.f90
src/physics/lsm_driver.f90
src/physics/lsm_noahmpdrv.f90
src/physics/water_lake.f90
src/physics/water_simple.f90

IMPORTANT: current procedure is to make changes to the develop branch and create pull requests into the develop branch. When making this Pull Reqest make sure to change the base branch to "develop".
TYPE:  enhancement
KEYWORDS: lake model, enhancement, bugfix water_simple
SOURCE: Bert Kruyt, NCAR
DESCRIPTION OF CHANGES: The lake model from WRF has been adapted for- and included into ICAR. now, selecting water=3 in the namelist runs this lakemodel for lake grid points, while the simple water model is used for ocean gridpoints. 
**changes to original code**
- nr of soil levels below lake points reduced from 10 to 4 
- the clauses that determine lake points on init has been slightly modified. 
**Requirements:**
- the LU_INDEX in the hi-res file should have a lake category. If this is not …

Enhancement/lake: inclusion of lake model, and fixes to water_simple/Noah

---

src/constants/icar_constants.f90
src/objects/exchangeable_obj.f90
src/physics/wind.f90

TYPE: bug fix
KEYWORDS: wind field, boundary conditions
DESCRIPTION OF CHANGES: Boundary conditions of the wind fields causes significant answer changes. The calculation of the the halo region bounds was slightly off for the wind fields.
ISSUE: The GitHub Issue that this PR addresses. For issue number 123, it would
be `Fixes #123`

Bugfix: wind boundary

---

src/objects/domain_h.f90
src/objects/domain_obj.f90
src/physics/wind.f90

TYPE: bug fix
KEYWORDS: wind fields, latitude, longitude, boundary conditions
DESCRIPTION OF CHANGES: Costheta and sintheta calculations were different when using one vs. multiple processes. To fix this lat and long fields are copied to global variables until costheta and sintheta are calculated. Slight changes to the bounds of certain calculations have been made
ISSUE: Fixes #146 
TESTS CONDUCTED: Comparing results from original code, 1 vs. 36 images  to the PR.
- Original: 1 vs 36 images
- 1 image (original) vs. 36 of PR Fix (note the orders of magnitude difference in the error color-bar needed to see any difference)

Issue 146 bugfix: costheta and sintheta calculations

---

run/complete_icar_options.nml
src/objects/boundary_h.f90
src/objects/boundary_obj.f90
src/objects/domain_obj.f90
src/objects/opt_types.f90
src/objects/options_obj.f90

TYPE: enhancement
KEYWORDS: pressure interpolation, forcing, sst, external precipitation, relative humidity
SOURCE: Ethan Gutmann, NCAR
This PR fixed a possible pressure interpolation bug and generally improved pressure vertical interpolation process significantly (**note** this can change precipitation, so far it seems to be an improvement)
This also adds namelist options to limit the relative humidity in the forcing data to, e.g. 120%, the minimum SST in the forcing to, e.g. 273.15K, and the maximum prescribed convective precipitation. All limit values are namelist options.
TESTS CONDUCTED: 
Ran multiple western US tests.  Tested model simulations that used to break as a result of bad pressure interpolation.  Tested that setting the SST, RH, or CP limits to very …

Fix/cmip stability v2.1.1

---

src/makefile

TYPE: bug fix
KEYWORDS: parallel build, Makefile
DESCRIPTION OF CHANGES: Running `make -j 4` was causing the following error
```
physics/water_simple.f90:10:9:
10 |     use options_interface,   only : options_t
|         1
Fatal Error: Cannot open module file ‘options_interface.mod’ for reading at (1): No such file or directory
compilation terminated.
```
Changed the Makefile to fix the compile dependencies. 
NOTE: This fix should also be applied to the `main` branch as well

Bugfix: parallel build

---

src/makefile
src/physics/lsm_noahmplsm.f90
src/physics/water_simple.f90

TYPE: bug fix
KEYWORDS: Cray, NoahMP, precision, compiler
SOURCE: Bert Kruyt, NCAR, RAL
DESCRIPTION OF CHANGES: makefile: water_simple now depends on options_h. Apparently gnu was ok without it, but cray is not. 
NoahMP: an error check in NoahMP that compares SWDOWN (downward solar filtered by sun angle [w/m2]) to the sum of FSA ( total absorbed solar radiation (w/m2)) and  FSR (total reflected solar radiation (w/m2)) gives an error if the difference is more than 0.01 W/m2. When compiled with cray, this condition is too stringent and the error is triggered. I increased the threshold to 0.1 W/m2.
TESTS CONDUCTED: runs - havent checked results but unlikely that <0.1 W/m2 makes a difference. Compiles with gfortran as well as cray (on Perlmutter)
Merging the PR depends on following checklist …

minor changes to make icar compile with cray and run 

---

.github/workflows/icar-develop-commit.yml
.github/workflows/icar-main-commit.yml
.github/workflows/icar-pull-request.yml

TYPE: bug fix
KEYWORDS: Github Actions, CI, Node.js
DESCRIPTION OF CHANGES: Github actions are returning a "Node.js 12 actions are deprecated." warning. This should fix the issue.
TESTS CONDUCTED: none, changes only affect Github Actions so the CI tests will let us know if it was successful. 

Bugfix: Fix 'node.js 12 deprecated' Message

---

src/makefile

TYPE: bugfix
KEYWORDS: Makefile, build system
DESCRIPTION OF CHANGES: water_simple requires `makefile` dependency change for parallel build.
TESTS CONDUCTED: built in parallel, tested up to `make -j 8`

bugfix: makefile parallel build

---

src/io/output_obj.f90

TYPE: bugfix
KEYWORDS: NetCDF, Valgrind
DESCRIPTION OF CHANGES: Valgrind was producing warnings of an uninitialized variable being used. The executable was outputting correct behavior because it would output `todays_date_time` with a bad value, then rewrite it later in the subroutine. Presumably this was originally done so that `todays_date_time` variable showed up in the NetCDF output in a specific order. Moving the `todays_date_time` initialization before the `nf90_put_att` call fixes the init issue and allows for removal of the repeat `nf90_put_att` call.
TESTS CONDUCTED: Builds and runs with correct looking output

bugfix: unititialized todays_date_time variable used

---

src/objects/exchangeable_h.f90
src/objects/exchangeable_obj.f90

TYPE: bugfix
KEYWORDS: windfields, halo exchange, boundary conditions
DESCRIPTION OF CHANGES: The halo exchange of the `u` and `v` variables doesn't communicate the diagonal values. These are needed for the windfield calculations to be performed correctly. Attempts were made to do a second halo exchange with just the single corner column but there is a bug in either Gfortran 12.1.0 or OpenCoarrays 2.10.1 that causes the `A(n,:,:)[neighbor]` assignment to occur incorrectly. 
TESTS CONDUCTED: Commented out `smooth_array` calls [here](https://github.com/NCAR/icar/blob/453dc64e508f549982724e93d73d6ed45da1bdf5/src/objects/domain_obj.f90#L2771) and [here](https://github.com/NCAR/icar/blob/453dc64e508f549982724e93d73d6ed45da1bdf5/src/objects/domain_obj.f90#L2792) …

bugfix: wind 3 physics n-cores differences

---

src/objects/exchangeable_h.f90
src/objects/exchangeable_obj.f90

TYPE: enhancement
KEYWORDS: halo exchange, wind 3 option
SOURCE: Soren Rasmussen's implementation and testing, Ethan's idea
DESCRIPTION OF CHANGES: More efficient halo communication for the u,v exchange. North/south communication and then east/west communication is performed instead of doing all u,v halo communication twice. The last PR #163 switched to performaing u,v halo communication twice to fix a bug. This had a hit on performance, while for the new PR the performance difference in negligible. 
TESTS CONDUCTED: Changes tested on the wind 3 option. When the two "smooth_array" lines are commented out the output of 32 vs 36 num processors is the same. I took a closer look at outputs at one of the corners and it looked correct. 
The "second PR" in the table is #163, the "original 1" is …

enhancement: better performance for wind 3 u,v exchange 

---

src/objects/domain_h.f90
src/objects/domain_obj.f90
src/objects/exchangeable_h.f90
src/objects/exchangeable_obj.f90
src/physics/linear_winds.f90

TYPE: bugfix
KEYWORDS: halo exchange, smoothing, linear winds
DESCRIPTION OF CHANGES:  bugfixes: 
1. `halo_size` changed from module variable to exchangeable_t type variable. Previous behavior meant the value used by the last grid to set halo_size was used for every exchangeable object going forward. Procedures that had used `halo_size` now have the additional line `halo_size = this%halo_size`, which fixes behavior without `this%` word "pollution".
2. wind=1 physics option was failing n-cores test due to smoothing behavior [here](https://github.com/NCAR/icar/blob/1bc194b245bb9115331e14ccaec3f29d472e3258/src/physics/linear_winds.f90#L981). New larger exchange_obj variable used to cover the extra area needed for the smooth function to pass n-cores tests. This …

bugfixes: halo_size and wind=1 smoothing

---

src/io/io_routines.f90
src/makefile
src/objects/options_obj.f90

TYPE: new feature
KEYWORDS: IO Files, Namelist Validation
DESCRIPTION OF CHANGES: New subroutine checks if output and restart file paths are writeable. When the namelist is read, the existence of the directories where the output and restart files are being written to is checked. If they do not exist the routine will report error then, rather than throwing an error later when the NetCDF library tries to write to the file.
TESTS CONDUCTED: Checked that the subroutine functioned correctly for the following input file strings
``` Fortran
output_file = "output/foo/icar_out_"
output_file = "output/icar_out_"
output_file = "output//icar_out_"
output_file = "./icar_out_"
output_file = "icar_out_"
```
issue describes and documents the problem and general solution, the …

Check if output and restart file path is writeable

---

src/io/io_routines.f90
src/io/lt_lut_io.f90
src/makefile
src/objects/options_obj.f90
src/physics/linear_winds.f90

TYPE: new feature
KEYWORDS: LUT, look-up table, coarrays
- The large LUT coarray has been changed to a regular array and two new smaller coarrays are used to communicate the data. This change has been done so the Cray compiler on Derecho can handle large LUT files.
- added check if to see if LUT file paths are writeable when reading namelist options
- there were issues with Crays debugslow mode causing issues with the the namelist being read incorrectly. Seems to be from the `-eZ` preprocessor option creating `.i` files mixed with some other compile options. The new preprocessor option is now `-eT`. The following shows the different preprocessor options and their descriptions
- Preprocessing flags: 
- `-eT` Control  preprocessing of …

New feature: non-coarray LUT

---

src/makefile

TYPE: bug fix
KEYWORDS: derived types, logical types, hack
DESCRIPTION OF CHANGES: If using the Cray compiler, turn off optimization when compiling the `options_obj.f90` file.
TESTS CONDUCTED: Add the following lines to line 1930 of `options_obj.f90`.
```
print*, "use_simple_sw, options%rad_options%use_simple_sw, rad_options%use_simple_sw"
print*, use_simple_sw, options%rad_options%use_simple_sw, rad_options%use_simple_sw
stop "debugging"
```
NOTE: The `-eo` compiler option lists all the optimization flags. Since `-O0` works and `-O1` does not, I could test each flag that is different individually to find which one is breaking this test. Might be worth it in case the optimization would break things somewhere else. I had previously tried to create a simple …

Bugfix: Cray logical derived type member values

---

src/physics/ra_clWRF_support.f90

TYPE: bugfix
KEYWORDS: read file, iso_fortran_env
DESCRIPTION OF CHANGES: The iso_fortran_env constant `iostat_end` has replaced the traditional, but not defined by the Fortran standard, `-1` to mean the end-of-file has been reached. This fix reflects that change that is starting to appear in some compilers.
TESTS CONDUCTED: The `CLWRF -- clwrf -- CLWRF ALERT!` [statement](https://github.com/scrasmussen/icar/blob/f295303f7eb19f6971714e4c3ff8e103c9026ef1/src/physics/ra_clWRF_support.f90#L177-L179) had started appearing with the Cray compiler 15.0.1, without any change to the "CAMtr_volume_mixing_ratio.SSP245" input file. This warning message is not showing up anymore.
Merging the PR depends on following checklist being completed. Add `X` between
each of the …

bugfix: CAMtr_volume_mixing_ratio read issue

---

docs/compiling.md

TYPE: text only
KEYWORDS: documentation, debugging, Derecho
- Added general and Derecho specific debugging information. Instructions on what to do when ICAR runs out of memory available to coarrays on large domains. 
- Updated Derecho module list
TESTS CONDUCTED: none

documentation: debugging information

---

helpers/aggregate_parallel_files.py

TYPE: ~~bug~~ issue fix
KEYWORDS: Xarray, Python, Aggregation
DESCRIPTION OF CHANGES: Fix for warning of a future switch in xarray. Just switched from `Dataset.dims` to `Dataset.sizes` in `aggregate_parallel_files.py` script to fix it. 
ISSUE: Fixes #182 
TESTS CONDUCTED: Compared results of new and previous aggregation script, they were identical.
```
$ nccmp -ds icar_out_2010-09-01_00-00-00.nc icar_out_2010-09-01_00-00-00.nc.orig
Files "icar_out_2010-09-01_00-00-00.nc" and "icar_out_2010-09-01_00-00-00.nc.orig" are identical.
```

Issue 182 Fix: Xarray Future Warning

---

.github/scripts/icar_install_utils.sh
.github/workflows/icar-develop-commit.yml
.github/workflows/icar-main-commit.yml
.github/workflows/icar-pull-request.yml
helpers/genNetCDF/Topography.py

TYPE: fix
KEYWORDS: Github Runner, CI, Version Bump
SOURCE: Soren Rasmussen, NSF NCAR
DESCRIPTION OF CHANGES: Bumping Ubuntu Github runner version from `20.04` to `latest`. Github Actions in a brownout for workflows still using `20.04`.

bugfix: Ubuntu runner bump to ubuntu-latest

---

docs/FAQ.md
docs/compiling.md

TYPE: fix
KEYWORDS: Derecho, Intel, ifx, broken links
DESCRIPTION OF CHANGES: Fixed broken FAQ links and added a warning about ifx/intel not working on Derecho because the coarray implementation needs `impi`, which Derecho doesn't have.
TESTS CONDUCTED: Built locally with mkdocs

documentation: mkdocs broken links and Intel info

---

.github/workflows/icar-develop-commit.yml
.github/workflows/icar-main-commit.yml
.github/workflows/icar-pull-request.yml

TYPE: hotfix
KEYWORDS: CI, Github Actions
SOURCE: Soren Rasmussen, NSF NCAR
DESCRIPTION OF CHANGES: Run CI only on upstream `NCAR/icar` repo, not forks. This is to prevent [charges to users](https://github.com/settings/billing).

hotfix: restrict CI to upstream
